name: cleaner_app
description: A Flutter application for cleaners to manage jobs, clock in/out, and track earnings
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

